# Generated by Django 3.2 on 2023-02-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profiles/default_profpic.png', null=True, upload_to='profiles/'),
        ),
    ]
