# Generated by Django 3.2 on 2023-02-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_conversation_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='last_message',
        ),
    ]
